name: Generar Playlist IPTV (Piped)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # Cada 6 horas

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: pip install requests

      - name: Generar Playlist
        run: |
          echo "[INFO] Ejecutando generación de playlist..."
          python youtube_to_googlevideo.py

      - name: Commit y Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add playlist.m3u raw_links.txt
          git commit --amend -m "Auto-update playlist" || git commit -m "Auto-update playlist"
          git push --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}