name: Update IPTV Playlist (Invidious)

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run IPTV Script
        run: |
          echo "[INFO] Generando playlist con Invidious..."
          python youtube_invidious_playlist.py

      - name: Validate playlist before commit
        run: |
          if [ ! -s playlist.m3u ]; then
            echo "[ERROR] Playlist vacía. No se subirá nada."
            exit 1
          fi
          if ! grep -q "http" playlist.m3u; then
            echo "[ERROR] Playlist inválida. No contiene enlaces."
            exit 1
          fi

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add playlist.m3u raw_links.txt
          if git diff --cached --quiet; then
            echo "[INFO] No hay cambios para commitear."
          else
            git commit -m "Auto-update playlist [skip ci]"
            git push
